### ISSUE TITLE
Improve structures: Point, Points

### ISSUE THREAD

**Issue by starius** [zer0main/battleship#1]
Please, provide the following members of structures Point and Points:
- [x] Points::isHorizontal() as a method, not as data member. It can be deduced from values of other fields, so it _IS TO_ be deduced.
- [x] Provide constructor for Point: Point(int row, int col)
- [x] Provide constructor for Points: Points(Point p1, Point p2)

Using constructors makes code much shorter and less error prone.

**Comment by zer0main** [comment]
Thanks for this issue. This part of work is completed now.
